[package]
name = "noise-xx"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9"
chacha20poly1305 = "0.9"
hkdf = "0.11"
x25519-dalek = "1.2"

[dev-dependencies]
snow = "0.8.0"
