[package]
name = "json-cbor"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
minicbor = { version = "0.12.0", features = ["half"] }
serde_json = "1.0.72"
