name: Liot Check

on:
  push:
    branches: [ main ]
    pull_request:
      branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test_json_cbor:
    runs-on: ubuntu-latest
    default:
      run:
        working_directory: ./json-cbor
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
  build_test_noise_xx:
    runs-on: ubuntu-latest
    default:
      run:
        working_directory: ./noise-xx
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
